src/Entity/Comments.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Stars;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="comments")
     */
    private $room;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="comments")
     */
    private $client;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getStars(): ?int
    {
        return $this->Stars;
    }

    public function setStars(int $Stars): self
    {
        $this->Stars = $Stars;

        return $this;
    }
    
    public function getRoom(): ?Room
    {
        return $this->room;
    }
    
    public function setRoom(?Room $room): self
    {
        $this->room = $room;
        
        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }
}

src/Entity/Room.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RoomRepository")
 * @Vich\Uploadable
 */
class Room
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $capacity;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $superficy;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Owner", inversedBy="room",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Region", inversedBy="room",cascade={"persist"})
     * 
     */
    private $regions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="resRoom")
     */
    private $reservations;
    
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Client", mappedBy="room",cascade={"persist"})
     *
     */
    private $clientlikes;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="room")
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @Vich\UploadableField(mapping="room", fileNameProperty="imageName")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $imageUpdatesAt;


    public function __toString() {
        return (string) $this->getSummary();
    }
    
    public function __construct()
    {
        $this->regions = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->imageUpdatesAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getSuperficy(): ?float
    {
        return $this->superficy;
    }

    public function setSuperficy(?float $superficy): self
    {
        $this->superficy = $superficy;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getOwner(): ?Owner
    {
        return $this->owner;
    }

    public function setOwner(?Owner $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @return Collection|Region[]
     */
    public function getRegions(): Collection
    {
        return $this->regions;
    }

    public function addRegion(Region $region): self
    {
        if (!$this->regions->contains($region)) {
            $this->regions[] = $region;
            $region->addRoom($this);
        }

        return $this;
    }

    public function removeRegion(Region $region): self
    {
        if ($this->regions->contains($region)) {
            $this->regions->removeElement($region);
            $region->removeRoom($this);
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setResRoom($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getResRoom() === $this) {
                $reservation->setResRoom(null);
            }
        }

        return $this;
    }
    
    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }
    
    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setRoom($this);
        }
        
        return $this;
    }
    
    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getRoom() === $this) {
                $comment->setResRoom(null);
            }
        }
        
        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageUpdatesAt(): ?\DateTimeInterface
    {
        return $this->imageUpdatesAt;
    }

    public function setImageUpdatesAt(?\DateTimeInterface $imageUpdatesAt): self
    {
        $this->imageUpdatesAt = $imageUpdatesAt;

        return $this;
    }

    /**
    * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
    * of 'UploadedFile' is injected into this setter to trigger the update. If this
    * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
        // It is required that at least one field changes if you are using doctrine
        // otherwise the event listeners won't be called and the file is lost
        $this->imageUpdatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }
}

src/Form/RoomType.php
<?php

namespace App\Form;

use App\Entity\Region;
use App\Entity\Room;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Vich\UploaderBundle\Form\Type\VichImageType;


class RoomType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('imageName', TextType::class,  [
            'label' => 'Image name',
            'label_attr' => [ 'class' => 'row-justify-center'],
            'attr' => [ 'class' => 'form-control'],
            'required' => false
        ])
        ->add('imageFile', VichImageType::class, [
            'label' => 'Choose an image',
            'label_attr' => [ 'class' => 'row-justify-center'],
            'attr' => [ 'class' => 'form-control-file'],
            'required' => false
        ])
        ->add('summary', TextType::class, [
            'label' => 'Summary',
            'label_attr' => [ 'class' => 'row-justify-center'],
            'attr' => [ 'class' => 'form-control']
        ])
        ->add('description', TextType::class, [
            'label' => 'Description',
            'label_attr' => [ 'class' => 'row-justify-center'],
            'attr' => [ 'class' => 'form-control']
        ])
        ->add('capacity', IntegerType::class,[
            'label' => 'Capacity',
            'label_attr' => [ 'class' => 'row-justify-center'],
            'attr' => [ 'class' => 'form-control']
        ])
        ->add('superficy',NumberType::class,[
            'label' => 'Superficy',
            'label_attr' => [ 'class' => 'row-justify-center'],
            'attr' => [ 'class' => 'form-control']
        ])
        ->add('price', NumberType::class,[
            'label' => 'Price',
            'label_attr' => [ 'class' => 'row-justify-center'],
            'attr' => [ 'class' => 'form-control']
        ])
        ->add('address', TextType::class, [
            'label' => 'Address',
            'label_attr' => [ 'class' => 'row-justify-center'],
            'attr' => [ 'class' => 'form-control']
        ])
        ->add('regions', EntityType::class ,[
            'class' => Region::class,
            'choice_label' => 'name',
            'multiple' => true,
            'expanded' => true,
            'label_attr' => [ 'class' => 'form-check-label checkboxLabel'],
            'choice_attr' => function($choice, $key, $value) {
                return ['class' => 'form-check-input checkboxX'];
            }
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Room::class,
        ]);
    }
}

src/Controller/RoomController.php
<?php

namespace App\Controller;

use App\Entity\Room;
use App\Form\RoomType;
use App\Repository\RoomRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/room")
 */
class RoomController extends AbstractController
{
    /**
     * @Route("/", name="room_index", methods={"GET"})
     *
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function index(RoomRepository $roomRepository): Response
    {
        return $this->render('room/index.html.twig', [
            'rooms' => $roomRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="room_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $room = new Room();
        if($this->getUser()){
            if ($this->getUser()->getAuthOwner()){
                 $room->setOwner($this->getUser()->getAuthOwner());
            }
        }
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($room);
            $entityManager->flush();
            $this->get('session')->getFlashBag()->add('message', 'Room added successfully!'); //message flash
            if($this->getUser()){
                if($this->getUser()->getAuthOwner())
                   return $this->redirectToRoute('room_list',array('id'=>$this->getUser()->getAuthOwner()->getId()));
             else
                    return $this->redirectToRoute('room_index');
            }
            return $this->redirectToRoute('room_index');
          
        }

        return $this->render('room/new.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }

   /* /**
     * @Route("/{id}", name="room_show", methods={"GET"})
     */
   /* public function show(Room $room): Response
    {
        return $this->render('room/show.html.twig', [
            'room' => $room,
        ]);
    }*/
    
    /**
     * @Route("/{id}", name="room_show", methods="GET")
     *
     * @param String $id
     *
     * @Security("is_granted('ROLE_OWNER') or is_granted('ROLE_ADMIN') or is_granted('ROLE_CLIENT')")
     */
    
    public function RoomShow($id)
    {
        
        $em = $this->getDoctrine()->getManager();
        
        $room = $em->getRepository(Room::class)->findOneBy(['id' => $id]);
        
        return $this->render('room/NoCRUDRoom.twig', array(
            'room' => $room,
            
        ));
    }

    /**
     * @Route("/{id}/edit", name="room_edit", methods={"GET","POST"})
     *
     * @Security("is_granted('ROLE_OWNER') or is_granted('ROLE_ADMIN')")
     *
     */
    public function edit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->get('session')->getFlashBag()->add('message', 'changes saved successfully!'); //message flash
            if($this->getUser()){
                if($this->getUser()->getAuthOwner())
                    return $this->redirectToRoute('room_list',array('id'=>$this->getUser()->getAuthOwner()->getId()));
                else
                        return $this->redirectToRoute('room_index');
                        
            }
            return $this->redirectToRoute('room_index');
            
        }

        return $this->render('room/edit.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }
    
   /* /**
     * @Route("/{id}/owneredit", name="room_owneredit", methods={"GET","POST"})
     */
  /*  public function Owneredit(Request $request, Room $room): Response
    {
        $form = $this->createForm(RoomType::class, $room);
        $form->remove('owner');                            #Removing the owner field
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('owner_list');
        }
        
        return $this->render('room/edit.html.twig', [
            'room' => $room,
            'form' => $form->createView(),
        ]);
    }*/

    /**
     * @Route("/{id}", name="room_delete", methods={"DELETE"})
     *
     * @Security("is_granted('ROLE_OWNER') or is_granted('ROLE_ADMIN')")
     */
    public function delete(Request $request, Room $room): Response
    {
        if ($this->isCsrfTokenValid('delete'.$room->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($room);
            $entityManager->flush();
        }

        return $this->redirectToRoute('room_index');
    }
}

templates/room/LikedRoom.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liked Room{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-9">
            <a href="javascript:history.back()" class="txt1" style="font-size: 18px"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp; Go back</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="section-heading text-center">
                <div class="line-"></div>
                <h1>This room has been {{ value }} your likes</h1>
            </div>
        </div>
    </div>

    <section class="contact-information-area">
        <div class="container">
            <div class="row">

                <div class="col-12 col-lg-4">
                    <div class="single-rooms-area wow fadeInUp" data-wow-delay="100ms">
                        <!-- Thumbnail -->
                        <div class="bg-thumbnail bg-img" style="background-image: url({{ vich_uploader_asset(room, 'imageFile') }});"></div>
                    </div>
                </div>

                <div class="col-6 col-lg-3"></div>

                <div class="col-12 col-lg-4">
                    <div class="single-contact-information mb-100">
                        <br><br><br><br>
                        <div class="section-text">
                            <h3>{{ room.summary }}</h3>
                            <p>{{ room.description }}</p>
                        </div>

                        <div class="contact-content d-flex">
                            <p>Address</p>
                            <p>{{ room.address }}</p>
                        </div>

                        <div class="contact-content d-flex">
                            <p>Capacity</p>
                            <p>{{ room.capacity }}</p>
                        </div>

                        <div class="contact-content d-flex">
                            <p>Superficy</p>
                            <p>{{ room.superficy }}</p>
                        </div>

                        <div class="contact-content d-flex">
                            <p>Price</p>
                            <p><strong>{{ room.price }} &euro;/night</strong></p>
                        </div>
                        <br>
                        <div class="contact-content d-flex">
                            {% if app.user %}

                                {%if app.user.ClientAuth %}
                                    <button class="btn palatin-btn btn-3 m-2"><a href="{{ path('reservation_new' , {'id' : room.id })  }}" >make a reservation</a></button>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

templates/room/NoCRUDRoom.twig
{% extends 'base.html.twig' %}  {#ROOM#}

{% block title %}Room{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-9">
            <a href="javascript:history.back()" class="txt1" style="font-size: 18px"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp; Go back</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="section-heading text-center">
                <div class="line-"></div>
                <h1>Room Info</h1>
            </div>
        </div>
    </div>

    <section class="contact-information-area">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-6">
                    <div class="single-rooms-area wow fadeInUp" data-wow-delay="100ms">
                        <!-- Thumbnail -->
                        <div class="bg-thumbnail bg-img" style="background-image: url( {{ vich_uploader_asset(room, 'imageFile') }} );"></div>
                    </div>
                </div>

                <div class="col-6 col-lg-2"></div>

                <div class="col-12 col-lg-4">
                    <div class="single-contact-information mb-100">
                        <br><br><br><br>
                        <div class="section-text">
                            <h2>{{ room.summary }}</h2>
                            <h5>{{ room.description }}</h5>
                        </div>

                        <div class="contact-content d-flex">
                            <p>Address</p>
                            <p>{{ room.address }}</p>
                        </div>

                        <div class="contact-content d-flex">
                            <p>Capacity</p>
                            <p>{{ room.capacity }}</p>
                        </div>

                        <div class="contact-content d-flex">
                            <p>Superficy</p>
                            <p>{{ room.superficy }}</p>
                        </div>

                        <div class="contact-content d-flex">
                            <p>Price</p>
                            <p><strong>{{ room.price }} &euro;/night</strong></p>
                        </div>
                               {% if app.user %}
        		{% if app.user.ClientAuth %}
        			<br><center><button  class="btn btn-info"><a  href="{{ path('reservation_new', {'id': room.id}) }}">Make a reservation!</a></button></center>
        		{% endif %}
        	{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="section-heading text-center">
                <div class="line-"></div>
                <h1>Room's comments</h1>
            </div>
        </div>
    </div>
    <br><br><br><br><br><br><br>
    {% for comment in room.comments %}
    <div class="blog-area section-padding-0-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="palatin-blog-posts">
                        <div class="single-blog-post mb-100 wow fadeInUp" data-wow-delay="100ms" style="visibility: visible; animation-delay: 100ms; animation-name: fadeInUp;">

                            <div class="post-content">
                                <a href="#" class="post-title">{{ comment.description }}</a>
                                <div class="post-meta d-flex justify-content-center">
                                    <a  class="post-catagory" style="font-size: 18px">Rating:
                                        {% if comment.stars == 1 %}
                                            <i class="fa fa-star"></i>
                                        {% elseif comment.stars == 2 %}
                                            <i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>
                                        {% elseif comment.stars == 3 %}
                                            <i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>
                                        {% elseif comment.stars == 4 %}
                                            <i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>
                                        {% elseif comment.stars == 5 %}
                                            <i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>&nbsp;<i class="fa fa-star"></i>
                                        {% endif%}
                                        
                                        {% if app.user %}
                                        	{% if not app.user.ClientAuth %}
                                        	<br>
                                        	{{ include('comments/_delete_form.html.twig') }}
                                        	{% endif %}
                                        	{% if app.user.ClientAuth %}
                                        		{% for cmnt in app.user.ClientAuth.comments  %}
                                        			{% if cmnt.id==comment.id %}
                                        				{{ include('comments/_delete_form.html.twig') }}
                                        		    {% endif %}
                                        		{% endfor %}
                                        				
                                        	{% endif %}
                                        {% endif %}
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
        <div class="blog-area section-padding-0-100">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="palatin-blog-posts">
                            <div class="single-blog-post mb-100 wow fadeInUp" data-wow-delay="100ms" style="visibility: visible; animation-delay: 100ms; animation-name: fadeInUp;">

                                <div class="post-content">
                                    <a href="#" class="post-title">No comments for this room</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}


{% endblock %}

templates/room/RoomsInRegion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rooms available{% endblock %}

{% block body %}

    <!-- ##### Rooms Area Start ##### -->
    <div class="row justify-content-center">
        <div class="col-md-9">
            <a href="javascript:history.back()" class="txt1" style="font-size: 18px"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp; Go back</a>
        </div>
    </div>

    <section class="rooms-area section-padding-0-100">
        <div class="row justify-content-center">
        </div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-6">
                    <div class="section-heading text-center">
                        <div class="line-"></div>
                        <h2>Rooms available in {{ region.name }}</h2>
                    </div>
                </div>
            </div>

            {% for room in rooms %}
                <div class="row">
                    <!-- Single Rooms Area -->
                    <div class="col-12 col-lg-4">
                        <div class="single-rooms-area wow fadeInUp" data-wow-delay="100ms">
                            <!-- Thumbnail -->
                            <div class="bg-thumbnail bg-img" style="background-image: url({{ vich_uploader_asset(room, 'imageFile') }});"></div>
                            <!-- Price -->
                            <p class="price-from">{{ room.price }}/night</p>
                            <!-- Rooms Text -->
                            <div class="rooms-text">
                                <div class="line"></div>
                                <h4>{{ room.summary }}</h4>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-lg-8">
                        <div class="about-text text-center mb-100">
                            <div class="section-heading text-center">
                                <div class="line-"></div>
                                <h3>{{ room.summary }}</h3>
                                <h5>{{ room.description }}</h5>
                            </div>
                            <p>Address: {{ room.address }}</p>
                            <div class="about-key-text">
                                <h6><span class="fa fa-check"></span> Superficy : {{ room.superficy }}</h6>
                                <h6><span class="fa fa-check"></span> Capacity : {{ room.capacity }}</h6>
                            </div>
                            <a href="{{ path('room_show', {'id': room.id}) }}" class="btn palatin-btn mt-50">More details!</a>
                            <a href="{{ path('like_add', {'id': room.id}) }}" class="btn palatin-btn mt-50">Add to Likes!</a>
                            <a href="{{ path('reservation_new', {'id': room.id}) }}" class="btn palatin-btn mt-50">Make a reservation!</a>
                            {% if app.user %}
                            	{% if app.user.ClientAuth %}
                                    {% set found = false %}
                            		{% for reservation in app.user.ClientAuth.reservations %}
                            			{% if (room.id==reservation.resRoom.id and not found) %}
                            					<a href="{{ path('comments_new', {'id': room.id}) }}" class="btn palatin-btn mt-50">Add a comment</a>
                                            {% set found = true %}
                           				{% endif %}
                           			{% endfor %}
                           		{% endif %}
                           	{% endif %}
                            
                      
                        </div>
                    </div>
                </div>


                {% else %}
                    <tr>
                        <td colspan="8">no records found</td>
                    </tr>
            {% endfor %}
        </div>
    </section>
    <!-- ##### Rooms Area End ##### -->

{% endblock %}

templates/room/_delete_form.html.twig
<form method="post" action="{{ path('room_delete', {'id': room.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ room.id) }}">
    {% if app.user %}
        {% if app.user.ClientAuth %}
        {% else %}
            <button class="btn btn-danger" id="buttonDelete">Delete</button>
        {% endif %}
    {% endif %}
</form>