src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 */
class Client
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ClFirstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ClFamilyName;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $ClCountry;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", mappedBy="ClientAuth", cascade={"persist", "remove"})
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="resClient")
     */
    private $reservations;
    
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Room", inversedBy="clientlikes",cascade={"persist"})
     */
    //,orphanRemoval=true
    private $room;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="client")
     */
    private $comments;
    
    public function __toString() {
        return (string) $this->getClFamilyname();
    }

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClFirstName(): ?string
    {
        return $this->ClFirstName;
    }

    public function setClFirstName(?string $ClFirstName): self
    {
        $this->ClFirstName = $ClFirstName;

        return $this;
    }

    public function getClFamilyName(): ?string
    {
        return $this->ClFamilyName;
    }

    public function setClFamilyName(string $ClFamilyName): self
    {
        $this->ClFamilyName = $ClFamilyName;

        return $this;
    }

    public function getClCountry(): ?string
    {
        return $this->ClCountry;
    }

    public function setClCountry(string $ClCountry): self
    {
        $this->ClCountry = $ClCountry;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        // set (or unset) the owning side of the relation if necessary
        $newClientAuth = $user === null ? null : $this;
        if ($newClientAuth !== $user->getClientAuth()) {
            $user->setClientAuth($newClientAuth);
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setResClient($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getResClient() === $this) {
                $reservation->setResClient(null);
            }
        }

        return $this;
    }
    
     /**
     * @return Collection|Room[]
     */
    public function getRoom(): Collection
    {
        return $this->room;
    }

    public function addRoom(Room $room): self
    {
        if (!$this->room->contains($room)) {
            $this->room[] = $room;
        }

        return $this;
    }

    public function removeRoom(Room $room): self
    {
        if ($this->room->contains($room)) {
            $this->room->removeElement($room);
        }

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setClient($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getClient() === $this) {
                $comment->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Comments.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Stars;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="comments")
     */
    private $room;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="comments")
     */
    private $client;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getStars(): ?int
    {
        return $this->Stars;
    }

    public function setStars(int $Stars): self
    {
        $this->Stars = $Stars;

        return $this;
    }
    
    public function getRoom(): ?Room
    {
        return $this->room;
    }
    
    public function setRoom(?Room $room): self
    {
        $this->room = $room;
        
        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CountryType;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ClFirstName', TextType::class, [
                'label' => 'First name',
                'label_attr' => [ 'class' => 'row-justify-center'],
                'attr' => [ 'class' => 'form-control']
            ])
            ->add('ClFamilyName', TextType::class, [
                'label' => 'Last name',
                'label_attr' => [ 'class' => 'row-justify-center'],
                'attr' => [ 'class' => 'form-control']
            ])
            ->add('ClCountry', TextType::class, [
                'label' => 'Country',
                'label_attr' => [ 'class' => 'row-justify-center'],
                'attr' => [ 'class' => 'form-control']
            ])
           /* ->add('FirstName',null,['property_path'=>'ClFirstName'])
            ->add('FamilyName',null,['property_path'=>'ClFamilyName'])
                ->add('Country',null,['property_path'=>'ClCountry'])*/
          
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\Room;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/", name="client_index", methods={"GET"})
     *
     * @Security("is_granted('ROLE_ADMIN')")
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="client_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $user=$client->getUser()->addRole('ROLE_CLIENT');
            $entityManager->persist($user);
            $entityManager->flush();
            $entityManager->persist($client);
            $entityManager->flush();
            $this->get('session')->getFlashBag()->add('message', 'Client added successfully!'); //message flash
            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_show", methods={"GET"})
     *
     * @Security("is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN')")
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="client_edit", methods={"GET","POST"})
     *
     * @Security("is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN')")
     *
     */
    public function edit(Request $request, Client $client): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->get('session')->getFlashBag()->add('message', 'changes saved successfully!'); //message flash
                
                    if($this->getUser()){
                        if($this->getUser()->getClientAuth())
                            return $this->redirectToRoute('client_profile',array('id'=>$client->getId()));
                         else 
                                return $this->redirectToRoute('client_index');
                                
                    }
                    return $this->redirectToRoute('client_index');

            
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_delete", methods={"DELETE"})
     *
     * @Security("is_granted('ROLE_ADMIN')")
     *
     */
    public function delete(Request $request, Client $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('client_index');
    }
    
    /**
     * @Route("/profile/{id}", name="client_profile", methods="GET")
     *
     * @param String $id
     *
     * @Security("is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN')")
     */
    public function ClientProfile($id)
    {

        $em = $this->getDoctrine()->getManager();
        
        $client = $em->getRepository(Client::class)->findOneBy(['id' => $id]);
        
        return $this->render('client/clientprofile.html.twig', array(
            'client' => $client,
            
        ));
    }
    
    /**
     * @Route("/{id}/reservations", name="client_reservations", methods="GET")
     *
     * @param String $id
     *
     * @Security("is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN')")
     */
    
    public function ClientReservations($id)
    {

        $em = $this->getDoctrine()->getManager();
        
        $client = $em->getRepository(Client::class)->findOneBy(['id' => $id]);
        $reservations = $client->getReservations();
        
        return $this->render('reservation/client_reservations.html.twig', [
            'reservations' => $reservations,
        ]);
    }
    
    
    /**
     * @Route("/{id}/likes", name="client_likes", methods="GET")
     *
     * @param String $id
     *
     * @Security("is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN')")
     */
    
    public function ClientLikes($id)
    {
        
        $em = $this->getDoctrine()->getManager();
        
        $client = $em->getRepository(Client::class)->findOneBy(['id' => $id]);
        $likes = $client->getRoom();
        
        return $this->render('client/ClientLikes.html.twig', [
            'rooms' => $likes,
        ]);
    }
    
    
    /**
     * @Route("/likeroom/{id}", name="like_add", methods="GET")
     *
     * @param String $id
     *
     * @Security("is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN')")
     */
    
    public function addLike($id)
    {
        
        $em = $this->getDoctrine()->getManager();
        
        $room = $em->getRepository(Room::class)->findOneBy(['id' => $id]);
        $client=$this->getUser()->getClientAuth();
        $client->addRoom($room);
        $em->persist($client);
        $em->flush();
        
        return $this->render('room/LikedRoom.html.twig', array('room'=>$room,'value'=>'added to')); 
    }
    
    /**
     * @Route("/deletelike/{id}", name="like_delete", methods="GET")
     *
     * @param String $id
     *
     * @Security("is_granted('ROLE_CLIENT') or is_granted('ROLE_ADMIN')")
     */
    
    public function deleteLike($id)
    {
        
        $em = $this->getDoctrine()->getManager();
        
        $room = $em->getRepository(Room::class)->findOneBy(['id' => $id]);
        $client=$this->getUser()->getClientAuth();
        $client->removeRoom($room);
        $em->persist($client);
        $em->flush();
        
        return $this->render('room/LikedRoom.html.twig', array('room'=>$room,'value'=>'removed from'));
    }
}

templates/client/ClientLikes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liked rooms{% endblock %}

{% block body %}

    <!-- ##### Rooms Area Start ##### -->
    <section class="rooms-area section-padding-0-100">
        <div class="row justify-content-center">
            <div class="col-md-9">
                <a href="javascript:history.back()" class="txt1" style="font-size: 18px"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp; Go back</a>
            </div>
        </div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-6">
                    <div class="section-heading text-center">
                        <div class="line-"></div>
                        <h2>Your Likes</h2>
                    </div>
                </div>
            </div>

            {% for room in rooms %}
                <div class="row">
                    <!-- Single Rooms Area -->
                    <div class="col-12 col-lg-4">
                        <div class="single-rooms-area wow fadeInUp" data-wow-delay="100ms">
                            <!-- Thumbnail -->
                            <div class="bg-thumbnail bg-img" style="background-image: url({{ vich_uploader_asset(room, 'imageFile') }});"></div>
                            <!-- Price -->
                            <p class="price-from">{{ room.price }}/night</p>
                            <!-- Rooms Text -->
                            <div class="rooms-text">
                                <div class="line"></div>
                                <h4>{{ room.summary }}</h4>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-lg-8">
                        <div class="about-text text-center mb-100">
                            <div class="section-heading text-center">
                                <div class="line-"></div>
                                <h2>{{ room.summary }}</h2>
                                <h5>{{ room.description }}</h5>
                            </div>
                            <p>Address : {{ room.address }}</p>
                            <div class="about-key-text">
                                <h6><span class="fa fa-check"></span> Superfacy : {{ room.superficy }}</h6>
                                <h6><span class="fa fa-check"></span> Capacity : {{ room.capacity }}</h6>
                            </div>
                            <a href="{{ path('room_show', {'id': room.id}) }}" class="btn palatin-btn mt-50">More details!</a>
                            <a href="{{ path('reservation_new', {'id': room.id}) }}" class="btn palatin-btn mt-50">Make reservation</a>
                            <a href="{{ path('like_delete', {'id': room.id}) }}" class="btn palatin-btn mt-50">Delete from likes</a>
                            {% if app.user %}
                            	{% if app.user.ClientAuth %}
                                    {% set found = false %}
                            		{% for reservation in app.user.ClientAuth.reservations %}
                            			{% if (room.id==reservation.resRoom.id and not found) %}
                            					<a href="{{ path('comments_new', {'id': room.id}) }}" class="btn palatin-btn mt-50">Add a comment</a>
                                            {% set found = true %}
                           				{% endif %}
                           			{% endfor %}
                           		{% endif %}
                           	{% endif %}
                            
                        </div>
                    </div>
                </div>


                {% else %}
                    <tr>
                        <td colspan="8">no records found</td>
                    </tr>
            {% endfor %}
        </div>
    </section>
    <!-- ##### Rooms Area End ##### -->

{% endblock %}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    {% if app.user %}
        {% if app.user.AuthOwner %}
        {% elseif app.user.ClientAuth %}
        {% else %}
			 <button class="btn btn-danger">Delete</button>
        {% endif %}
    {% endif %}
</form>

templates/client/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            {{ form_row(form.ClFirstName) }}
        </div>
    </div>
</div>

<div class="form-group">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            {{ form_row(form.ClFamilyName) }}
        </div>
    </div>
</div>

<div class="form-group">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            {{ form_row(form.ClCountry) }}
        </div>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-md-3 offset-md-1">
        <button class="btn btn-success">{{ button_label|default('Save') }}</button>
    </div>
</div>
{{ form_end(form) }}

templates/client/clientprofile.html.twig
{% extends 'base.html.twig' %} {#CLIENT PROFILE#}

{% block title %}{{ client.ClFamilyName }}'s profile{% endblock %}


{% block body %}
    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="section-heading text-center">
                <div class="line-"></div>
                <h1>Welcome {% if client.ClFirstName %} {{ client.ClFirstName }}{% endif %} {{ client.ClFamilyName}}</h1>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-12 col-md-3"></div>
        <div class="col-12 col-md-1">
            <a href="/selectregion" class="txt1" style="font-size : 20px">
                <div class="single-cool-fact mb-100">
                    <div class="scf-text">
                        <i class="fa fa-calendar"></i>
                        <h4 style="color: white">Make a reservation</h4>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-1 ml-auto">
            <a href="{{ path('client_likes', {'id': client.id}) }}" class="txt1" style="font-size : 20px">
                <div class="single-cool-fact mb-100">
                    <div class="scf-text">
                        <i class="fa fa-heart"></i>
                        <h4 style="color: white">Check my liked rooms</h4>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-1 ml-auto">
            <a href="{{ path('client_reservations', {'id': client.id}) }}" class="txt1" style="font-size : 20px">
                <div class="single-cool-fact mb-100">
                    <div class="scf-text">
                        <i class="fa fa-calendar-check-o"></i>
                        <h4 style="color: white">Check my reservations</h4>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-1 ml-auto">
            <a href="{{ path('client_edit', {'id': client.id}) }}" class="txt1" style="font-size : 20px">
                <div class="single-cool-fact mb-100">
                    <div class="scf-text">
                        <i class="fa fa-user"></i>
                        <h4 style="color: white">Modify my profile</h4>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-12 col-md-3 ml-auto"></div>

    </div>
    
{% endblock %}

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profile{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-9">
            <a href="javascript:history.back()" class="txt1" style="font-size: 18px"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp; Go back</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="section-heading text-center">
                <div class="line-"></div>
                <h1>Edit Client Profile</h1>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            {{ include('client/_form.html.twig', {'button_label': 'Update'}) }}
        </div>
    </div>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-3 offset-md-2">
            {{ include('client/_delete_form.html.twig') }}
        </div>
    </div>

{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client index{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-9">
            <a href="javascript:history.back()" class="txt1" style="font-size: 18px"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp; Go back</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-3 offset-md-3"></div>
        <div class="col-md-3 offset-md-3">
            <a href="{{ path('client_new') }}" class = "btn btn-success" style="font-size: 18px">Add a new client</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="section-heading text-center">
                <div class="line-"></div>
                <h1>Client index</h1>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-2"></div>
        <div class="col">

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>FirstName</th>
                        <th>FamilyName</th>
                        <th>Country</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for client in clients %}
                    <tr>
                        <td>{{ client.id }}</td>
                        <td>{{ client.ClFirstName }}</td>
                        <td>{{ client.ClFamilyName }}</td>
                        <td>{{ client.ClCountry }}</td>
                        <td>
                            <a href="{{ path('client_show', {'id': client.id}) }}" style="color:blue;font-size: 16px">show</a>
                            <a href="{{ path('client_edit', {'id': client.id}) }}" style="color:indianred;font-size: 16px">&nbsp;&nbsp;&nbsp;edit</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>

        <div class="col-12 col-md-2"></div>
    </div>

{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Client{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-9">
            <a href="javascript:history.back()" class="txt1" style="font-size: 18px"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp; Go back</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="section-heading text-center">
                <div class="line-"></div>
                <h1>Create new Client</h1>
            </div>
        </div>
    </div>

    {{ include('client/_form.html.twig') }}
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-md-9">
            <a href="javascript:history.back()" class="txt1" style="font-size: 18px"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;&nbsp; Go back</a>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="section-heading text-center">
                <div class="line-"></div>
                <h1>Client</h1>
            </div>
        </div>
    </div>

<div class="row">
    <div class="col-12 col-lg-4"></div>
    <div class="col-12 col-lg-4">

        <table class="table table-hover">
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ client.id }}</td>
                </tr>
                <tr>
                    <th>ClFirstName</th>
                    <td>{{ client.ClFirstName }}</td>
                </tr>
                <tr>
                    <th>ClFamilyName</th>
                    <td>{{ client.ClFamilyName }}</td>
                </tr>
                <tr>
                    <th>ClCountry</th>
                    <td>{{ client.ClCountry }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="col-12 col-lg-4"></div>
</div>

    <div class="row justify-content-center">
        <div class="col-lg-5"></div>
        <div class="col-lg-1 text-center form-group">
            {{ include('client/_delete_form.html.twig') }}
        </div>
        <div class="col-lg-1">
            <button class="btn btn-success w-50 h-75"><a href="{{ path('client_edit', {'id': client.id}) }}" style="font-size: 16px;color: white">Edit</a></button>
        </div>
        <div class="col-lg-5"></div>
    </div>

{% endblock %}